-- Seed Data for Testing Service Marketplace
-- Run this after master_schema.sql

-- Insert test service provider (Pro user)
-- Note: This assumes op.younis@gmail.com will sign up as a Pro user
-- The actual user ID will be generated by Supabase Auth

-- Sample Services (will be inserted via the app, but here's the structure for reference)
-- INSERT INTO services (provider_id, title, description, category, base_price, location, capacity, images, features)
-- VALUES (
--   'USER_ID_HERE',
--   'قاعة الأفراح الملكية',
--   'قاعة فخمة تتسع لـ 500 ضيف مع إضاءة LED وديكور حديث',
--   'venue',
--   15000.00,
--   'الرياض - حي النرجس',
--   500,
--   '["https://images.unsplash.com/photo-1519167758481-83f29da8c9a7"]'::jsonb,
--   '["إضاءة LED", "نظام صوت احترافي", "مواقف سيارات", "مكيفات مركزية"]'::jsonb
-- );

-- Sample Promotional Code
INSERT INTO promotional_codes (code, discount_type, discount_value, min_purchase, max_uses, valid_until)
VALUES 
  ('WELCOME50', 'percentage', 10, 1000, 100, now() + interval '30 days'),
  ('FIRSTBOOK', 'fixed', 500, 5000, 50, now() + interval '60 days')
ON CONFLICT (code) DO NOTHING;

-- Note: Actual service data will be created through the admin interface
